### PR TITLE
[TASK] Streamline code formatting

### PR DESCRIPTION
**Pull request by Akii**
As discussed in PR 18:

* Newline after opening php tag and namespace
* lowerCamelCase for all variable names (including function args)

Additionally I generated PHPDoc comments for all classes.

### CODE REVIEW

**Comment by Akii** [comment]
Forgot to rebase, WIP :)

**Comment by dbellettini** [comment]
Yes, it looks like it's based on a very old version of code (prior to Broadway driver extraction)

**Comment by Akii** [comment]
Should be OK now.

**Comment by dbellettini** [comment]
:+1: for this, postponed after #18 merge

**Pull request merged**
